language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  - PREFER_LOWEST=""
  - PREFER_LOWEST="--prefer-lowest"

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction $PREFER_LOWEST

script: composer testci
